Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'

  # sync by copying for isolation
  config.vm.synced_folder "..", "/dotbot", type: "rsync",
    rsync__exclude: ".git/"

  # disable default synced folder
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
